mv cmd job to special_jobs
libi/dcron pull request #53
Opened 2023-05-11 07:31 UTC by libi

2023-05-16 03:46 UTC, libi commented
这个实现我觉得还能优化一下，主要有两个：
1. bash 命令应该存在需要接收命令执行结果的需求，需要修改实现。
2. 单次执行多条 bash 可以改为单条简化执行逻辑。多条可以通过多个job实现，某些场景下需要单job多bash语句，可以用bash语句的 && 。

2023-05-24 02:38 UTC, libi commented
@dxyinme 帮看下这个pr还有啥问题没

2023-05-24 03:13 UTC, dxyinme commented
> @dxyinme 帮看下这个pr还有啥问题没

欸我提了一些review意见是没显示嘛

2023-05-24 03:13 UTC, dxyinme requested changes

2023-05-24 03:13 UTC, dxyinme commented on special_jobs/job_bash.go
> +	job.Logger.Infof("------ " + cmdStr + " ----\n" + stdOut.String() + " ----\n" + stdErr.String())
ping

2023-05-24 03:13 UTC, dxyinme commented on special_jobs/job_bash.go
> +			cmd = exec.CommandContext(ctx, "sh", "-c", job.Cmd)
这里依旧还是老问题

2023-05-24 03:14 UTC, dxyinme commented
> @dxyinme 帮看下这个pr还有啥问题没

淦，要request changes才行

2023-05-24 03:17 UTC, libi commented
哈哈 review意见我这看不到 那另一个pr我提的意见你是不是也看不见啊

2023-05-24 03:22 UTC, dxyinme commented
> 哈哈 review意见我这看不到 那另一个pr我提的意见你是不是也看不见啊。 我也一直以为review评论就会显示🤣

看不着，我之前也以为review了就会显示，好难用啊这,,,

2023-05-24 03:22 UTC, dxyinme requested changes
review

2023-05-24 03:25 UTC, libi commented on dcron.go
> +func (d *Dcron) AddCmd(jobName, cronStr string, cmds []string, execTimeout time.Duration) (err error) {
好主意👍 提高扩展性同时能保持对外方法统一性

2023-05-24 03:31 UTC, libi commented
看了下文档 🤕️确实就是这么设计的 https://docs.github.com/zh/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request

提交审查之前，你的行注释为“待处理”状态并且仅对你可见。 您可以在提交审查之前随时编辑待处理的注释。 若要取消挂起的审查（包括其所有挂起的注释），请单击已更改的代码上方的“审查更改”，然后单击“取消审查”。

2023-05-24 11:17 UTC, dxyinme approved these changes

2023-05-24 11:18 UTC, merged